<?= $this->include('partials/visual_header', ['titulo' => 'Aprovação de cadastros - Achei Profissional']) ?>
<main class="page">
    <h1 class="page-title">Aprovação de cadastros</h1><p class="page-subtitle">Revise os novos profissionais e contratantes antes da publicação na plataforma.</p>
    <div class="notice"><i class="bi bi-shield-check me-1"></i> Área administrativa demonstrativa. As ações abaixo ainda não alteram os cadastros.</div>
    <section class="card"><div class="grid-3"><div><label class="label">Status</label><select class="select"><option>Pendentes</option><option>Aprovados</option><option>Rejeitados</option></select></div><div><label class="label">Tipo de cadastro</label><select class="select"><option>Todos</option><option>Profissional</option><option>Contratante</option></select></div><div><label class="label">Pesquisar</label><input class="input" placeholder="Nome ou e-mail"></div></div></section>
    <section class="card"><h2>Cadastros pendentes <span style="color:var(--muted);font-size:12px;font-weight:normal">4 aguardando análise</span></h2><div style="border-top:1px solid #edf1f4;padding:16px 0;display:flex;justify-content:space-between;gap:15px;align-items:center"><div><strong>Rafael Serviços Elétricos</strong><div class="hint">Profissional · Eletricista · Enviado hoje às 09:42</div></div><div class="actions" style="margin:0"><button class="btn" type="button">Visualizar</button><button class="btn" type="button">Rejeitar</button><button class="btn primary" type="button">Aprovar</button></div></div><div style="border-top:1px solid #edf1f4;padding:16px 0;display:flex;justify-content:space-between;gap:15px;align-items:center"><div><strong>Beatriz Almeida</strong><div class="hint">Contratante · Juiz de Fora · Enviado ontem</div></div><div class="actions" style="margin:0"><button class="btn" type="button">Visualizar</button><button class="btn" type="button">Rejeitar</button><button class="btn primary" type="button">Aprovar</button></div></div><div style="border-top:1px solid #edf1f4;padding:16px 0;display:flex;justify-content:space-between;gap:15px;align-items:center"><div><strong>Lucas Pinturas</strong><div class="hint">Profissional · Pintor · Enviado ontem</div></div><div class="actions" style="margin:0"><button class="btn" type="button">Visualizar</button><button class="btn" type="button">Rejeitar</button><button class="btn primary" type="button">Aprovar</button></div></div></section>
    <a class="btn" href="<?= site_url('admin') ?>">Voltar ao painel</a>
</main>
</body></html>
