<?= $this->include('partials/visual_header', ['titulo' => 'Cadastro profissional - Achei Profissional']) ?>
<main class="page">
    <h1 class="page-title">Cadastro profissional</h1><p class="page-subtitle">Apresente seu trabalho e seja encontrado por contratantes da sua região.</p>
    <div class="notice"><i class="bi bi-eye me-1"></i> Prévia visual do cadastro. Os campos ainda não serão salvos.</div>
    <form>
        <section class="card"><h2>Foto e dados básicos</h2><div class="upload"><div class="avatar">JS</div><div><label class="label" for="foto">Foto de perfil</label><input class="input" id="foto" type="file" accept="image/*"><div class="hint">Use uma imagem nítida do profissional ou da marca.</div></div></div><div class="grid-2"><div><label class="label" for="nome">Nome de exibição</label><input class="input" id="nome" value="João Eletricista"></div><div><label class="label" for="tipo">Tipo de pessoa</label><select class="select" id="tipo"><option>Pessoa física</option><option>Pessoa jurídica</option></select></div></div><div class="grid-2"><div><label class="label" for="documento">CPF ou CNPJ</label><input class="input" id="documento" placeholder="000.000.000-00"></div><div><label class="label" for="whatsapp">WhatsApp</label><input class="input" id="whatsapp" placeholder="(00) 00000-0000"></div></div></section>
        <section class="card"><h2>Categorias de atuação</h2><label class="label" for="categoria">Adicionar categorias</label><select class="select" id="categoria"><option>Selecione uma categoria</option><option>Eletricista</option><option>Instalações elétricas</option><option>Energia solar</option><option>Manutenção residencial</option></select><div class="chips"><span class="chip">Eletricista ×</span><span class="chip">Instalações elétricas ×</span><span class="chip">Manutenção residencial ×</span></div></section>
        <section class="card"><h2>Localização e área de atuação</h2><div class="grid-3"><div><label class="label">Estado</label><select class="select"><option>MG</option></select></div><div><label class="label">Cidade</label><select class="select"><option>Muriaé</option><option>Juiz de Fora</option></select></div><div><label class="label">Bairro</label><select class="select"><option>Centro</option><option>Barra</option></select></div></div><div class="chips"><span class="chip">Centro, Muriaé ×</span><span class="chip">Barra, Muriaé ×</span></div><label class="label" for="descricao">Descrição profissional</label><textarea class="textarea" id="descricao" placeholder="Conte um pouco sobre seus serviços"></textarea></section>
        <section class="card"><h2>Horário de expediente</h2><div class="grid-3"><div><label class="label">Dia inicial</label><select class="select"><option>Segunda-feira</option></select></div><div><label class="label">Abertura</label><input class="input" type="time" value="08:00"></div><div><label class="label">Fechamento</label><input class="input" type="time" value="18:00"></div></div><div class="hint">A agenda completa poderá ser configurada posteriormente.</div></section>
        <div class="actions"><a class="btn" href="<?= site_url('busca') ?>">Cancelar</a><button class="btn primary" type="button">Salvar perfil</button></div>
    </form>
</main>
</body></html>
