<?= $this->include('partials/visual_header', ['titulo' => 'Cadastro de contratante - Achei Profissional']) ?>
<main class="page">
    <h1 class="page-title">Cadastro de contratante</h1><p class="page-subtitle">Crie seu perfil para encontrar profissionais e solicitar serviços.</p>
    <div class="notice"><i class="bi bi-eye me-1"></i> Prévia visual do cadastro. Os dados serão integrados posteriormente.</div>
    <form>
        <section class="card"><h2>Foto e dados pessoais</h2><div class="upload"><div class="avatar">AP</div><div><label class="label" for="foto">Foto de perfil</label><input class="input" id="foto" type="file" accept="image/*"><div class="hint">A foto ajuda a personalizar seu perfil.</div></div></div><div class="grid-2"><div><label class="label" for="nome">Nome completo</label><input class="input" id="nome" value="Ana Paula Souza"></div><div><label class="label" for="tipo">Tipo de pessoa</label><select class="select" id="tipo"><option>Pessoa física</option><option>Pessoa jurídica</option></select></div></div><div class="grid-2"><div><label class="label" for="documento">CPF ou CNPJ</label><input class="input" id="documento" placeholder="000.000.000-00"></div><div><label class="label" for="email">E-mail</label><input class="input" id="email" type="email" value="ana@email.com"></div></div></section>
        <section class="card"><h2>Contato e localização</h2><div class="grid-2"><div><label class="label" for="telefone">Telefone</label><input class="input" id="telefone" placeholder="(00) 0000-0000"></div><div><label class="label" for="whatsapp">WhatsApp</label><input class="input" id="whatsapp" placeholder="(00) 00000-0000"></div></div><div class="grid-3"><div><label class="label">Estado</label><select class="select"><option>MG</option></select></div><div><label class="label">Cidade</label><select class="select"><option>Juiz de Fora</option><option>Muriaé</option></select></div><div><label class="label">Bairro</label><select class="select"><option>Centro</option><option>São Mateus</option></select></div></div></section>
        <section class="card"><h2>Categorias de interesse</h2><p class="hint">Escolha os tipos de profissionais que você procura com mais frequência.</p><div class="chips"><span class="chip">Eletricista ×</span><span class="chip">Encanador ×</span><span class="chip">Pintor ×</span></div><select class="select" style="margin-top:12px"><option>Adicionar categoria</option><option>Fotógrafo</option><option>Designer</option><option>Jardineiro</option></select></section>
        <div class="actions"><a class="btn" href="<?= site_url('cadastro') ?>">Voltar</a><button class="btn primary" type="button">Salvar cadastro</button></div>
    </form>
</main>
</body></html>
